name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 13.232.38.226
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/devops-app
            git pull origin main
            pm2 restart devops-app
